# Numpy
> Numpy (Numerical Python) adalah standar universal untuk bekerja dengan data numerik menggunakan Python, dan merupakan inti dari ekosistem ilmiah Python dan PyData
Numpy menyediakan multidimensional array, array pada numpy lebih cepat dan lengkap dibandingakn dengan list pada python

Semua elemen dalam array numpy harus bersifat homogen.

In [1]:
import numpy as np

In [5]:
# Menginisialisasi array numpy
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# memanggil berdasarkan index
print(a[0])
print()
print(a[0][0])

[1 2 3 4]

1


## Attributes of an array
Dalam numpy, dimensi disebut axes. Artinya jika kita memiliki array seperti ini:

> [[0,2,0,4],
 [2,3,4,6]]

Berarti array kita memiliki 2 axes. Axis pertama panjang 2 dan axis kedua memiliki panjang 3

### Contruction an array

In [7]:
# Membuat array numpy
n = np.array([1,2,3])
n

array([1, 2, 3])

In [8]:
np.zeros(4)

array([0., 0., 0., 0.])

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.empty(7)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 2.33644129e-307,
       1.42413555e-306, 1.78019082e-306, 6.23061762e-307])

In [11]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
np.arange(1,20,1) # (start, stop, step)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [13]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Add, remove, and sort
* np.append()
* np.delete()
* np.sort()

In [20]:
# Add to array
arr = np.append(arr, [20,21])
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 20, 21])

In [22]:
# Menghapus elemen di index 1
arr = np.delete(arr, 1)
arr

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 20, 21])

In [23]:
# Mengurutkan angka dengan menaik
arr = np.sort(arr)
arr

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 20, 21, 21])

### Shape and Size
* ndarray.ndim()
* ndarray.size()
* ndarray.shape()

In [37]:
multi = np.array([
    [
        [1,2,3,4,5],
        [6,7,8,9,10]
    ],
    [
        [11,12,13,14,15],
        [16,17,18,19,20]
    ],
    [
        [21,22,23,24,25],
        [26,27,28,29,30]
    ]
])

In [33]:
# Dimensi array
multi.ndim

3

In [34]:
# Total elemen array
multi.size

30

In [35]:
# shape array
multi.shape

(3, 2, 5)

### Reshape
* np.reshape() => memberikan bentuk baru pada array tanpa merubah datanya.

In [50]:
arr.size

32

In [49]:
# kita bisa merubah shape array tersebut, sbg contoh kita bisa merubah 
# menjadi bentuk 4 baris dan 8 kolom
arr_multi = arr.reshape(4,8)
arr_multi

array([[ 0,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 20, 21, 21, 22],
       [22, 22, 22, 23, 22, 23, 23, 23]])

In [51]:
arr_multies = arr.reshape(4,4,2)
arr_multies

array([[[ 0,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [20, 21],
        [21, 22]],

       [[22, 22],
        [22, 23],
        [22, 23],
        [23, 23]]])

In [52]:
# atau menggunakan format ini 
# numpy.reshape(nama_array, bentuk_baru, order)

### Convert 1D to 2D
* np.newaxis
> Untuk meningkatkan dimensi array sebesar 1 dimensi bila digunakan sekali. Artinya array 1D akan menjadi array 2D, array 2D akan menjadi array 3D, dst.
* np.expand_dims

In [57]:
con = np.arange(6)
print(con)
con.shape

[0 1 2 3 4 5]


(6,)

In [58]:
con2 = con[np.newaxis]
print(con2)
con2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [62]:
con3 = con[np.newaxis, :]
print(con3.shape)
print(con3)

(1, 6)
[[0 1 2 3 4 5]]


In [63]:
con3 = con[:, np.newaxis]
print(con3.shape)
print(con3)

(6, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [69]:
# Add axis to index position 0:
b = np.expand_dims(b, axis=0)
b.shape
print(b)

[[[[[ 1  2  3  4]]

   [[ 5  6  7  8]]

   [[ 9 10 11 12]]]]]


In [70]:
# Add axis to index position 1:
c = np.expand_dims(a, axis=1)
c.shape
print(c)

[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


In [68]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Indexing and Slicing

In [73]:
data = np.arange(3)
data

array([0, 1, 2])

In [74]:
data[0]

0

In [75]:
data[0:2]

array([0, 1])

In [76]:
data[-2:]

array([1, 2])

In [77]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
# five_up
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [80]:
# Divisible by 2
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [81]:
# Between 2 condition
a[(a>2) & (a<11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

### Creating Array from Existing Data
Slicing indexing
* np.vstack()
* np.hstack()
* np.hsplit()
* .view()
* .copy()

In [84]:
new = np.arange(10)
new

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
new1 = new[3:8]
new1

array([3, 4, 5, 6, 7])

In [87]:
a_1 = np.array([[1, 1],
                [2, 2]])
a_2 = np.array([[3, 3],
                [4, 4]])

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [88]:
# Menumpuk 2 array secara vertikal
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [89]:
# Menumpuk 2 array secara Horizontal
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [95]:
# Membagi array
arrsplit = np.array([[1,2,3,4,5,6,7,8,11],
                      [9,10,11,12,13,14,15,16,21]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8 11]
 [ 9 10 11 12 13 14 15 16 21]]


In [96]:
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3],
        [ 9, 10, 11]]),
 array([[ 4,  5,  6],
        [12, 13, 14]]),
 array([[ 7,  8, 11],
        [15, 16, 21]])]

In [98]:
# Create new array that looks at the same data
b = arrsplit.view()
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8, 11],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 21]])

In [99]:
# Make a copy
c = arrsplit.copy()
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8, 11],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 21]])

### Basic Array Operation
* addition
* substraction
* multiplication
* division 
* etc

In [3]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
a.sum()

66

In [6]:
b = np.array([[1,1], [2,2]])
b

array([[1, 1],
       [2, 2]])

In [11]:
# Menjumlahkan baris
c = b.sum(axis=0)
c

array([3, 3])

In [12]:
# Menjumlahkan kolom
d = b.sum(axis=1)
d

array([2, 4])

In [13]:
c + d

array([5, 7])

In [14]:
c * d

array([ 6, 12])

In [15]:
c / d

array([1.5 , 0.75])

### Broadcasting
Operasi antara suatu array dengan bilangan.

Broadcasting adalah mekanisme yang memungkinkan array melakukan operasi pada array dengan bentuk yang berbeda. Dimensinya harus kompatibel.

In [16]:
c * 2

array([6, 6])

### More array Operation
* max()
* min()
* sum()
* mean
* product
* standar deviation
* etc

In [17]:
c.sum()

6

In [18]:
a.min()

0

In [19]:
a.min(axis=0)

0

In [20]:
b.min(axis=1)

array([1, 2])

In [21]:
a.std()

3.452052529534663

In [22]:
b.std()

0.5

### Matrices


In [23]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
np.random.random((3,2))

array([[0.32094085, 0.86096312],
       [0.49191345, 0.87775347],
       [0.11173258, 0.55200005]])

In [26]:
# Perkalian matriks (dot ptoduct)
a = np.ones((2,3))
b = np.ones((3,2))
np.dot(a,b)

array([[3., 3.],
       [3., 3.]])

In [27]:
data = np.array([[1,2], [3,4],[5,6]])

print(data[0:2,1])

[2 4]


In [28]:
data[0:3]

array([[1, 2],
       [3, 4],
       [5, 6]])

### Transposing and Reshaping


In [29]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [31]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
arr = np.arange(6).reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [37]:
np.random.random((4,3,4))

array([[[6.64195118e-02, 1.08847993e-01, 1.00138627e-01, 9.72349885e-02],
        [7.23846658e-01, 3.86253729e-01, 9.93433584e-01, 6.79519663e-01],
        [3.53334290e-01, 3.44715636e-04, 3.73367258e-01, 1.84870235e-01]],

       [[3.54497169e-01, 2.87123934e-01, 1.44063350e-01, 2.78772722e-01],
        [4.72952770e-01, 4.10320016e-01, 3.99781173e-01, 5.71644639e-01],
        [2.32829607e-01, 7.47127136e-01, 5.99021686e-01, 8.92497759e-01]],

       [[6.72793581e-01, 6.05893131e-01, 2.47055094e-01, 7.98704070e-01],
        [9.32026249e-01, 3.48160982e-01, 3.78926594e-02, 2.29214651e-01],
        [9.72873210e-01, 5.62909850e-01, 9.67062154e-01, 9.08339273e-01]],

       [[1.67185239e-01, 7.31091651e-01, 3.16990128e-01, 8.29775220e-01],
        [8.81601117e-01, 6.22642764e-01, 4.08011000e-01, 3.87507802e-01],
        [3.64062182e-01, 1.54181119e-01, 8.76881172e-01, 2.92835066e-01]]])

### Meratakan aray 
* .flatten() => membuat salinan array baru
* .ravel() => perubahan juga berpengaruh ke array induk

In [38]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [39]:
arr.flatten()

array([0, 1, 2, 3, 4, 5])

In [40]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
arr.ravel()

array([0, 1, 2, 3, 4, 5])

In [43]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

### Menerapkan rumus ke numpy

In [45]:
n = 3
observed = 75
prediction = 70

# Rumus mean square error => rumus utama yang digunakan dalam supervised 
# machine learning model yang menangani regresi
error = (1/n) * np.sum(np.square(observed - prediction))
error

8.333333333333332

In [46]:
# np.square untuk kuadrat